export const CREATE_CHECKOUT_SESSION_SUCCESS = "CREATE_CHECKOUT_SESSION_SUCCESS";
export const CREATE_CHECKOUT_SESSION_FAILURE = "CREATE_CHECKOUT_SESSION_FAILURE";
export const REDIRECT_TO_CHECKOUT_SUCCESS = "REDIRECT_TO_CHECKOUT_SUCCESS";
export const REDIRECT_TO_CHECKOUT_FAILURE = "REDIRECT_TO_CHECKOUT_FAILURE";
export const CREATE_CHECKOUT_SESSION_REQUEST = "CREATE_CHECKOUT_SESSION_REQUEST";
export const REDIRECT_TO_CHECKOUT_REQUEST = "REDIRECT_TO_CHECKOUT_REQUEST";
export const GET_PAYMENT_DATA_SUCCESS = "GET_PAYMENT_DATA_SUCCESS";
export const GET_PAYMENT_DATA_FAILURE = "GET_PAYMENT_DATA_FAILURE";
