export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";

export const DELETE_EVENT_FAILED = "DELETE_EVENT_FAILED";
export const UPDATE_EVENT_FAILED = "UPDATE_EVENT_FAILED";
export const ADD_EVENT_FAILED = "ADD_EVENT_FAILED";

export const SYNC_EVENT_SUCCESS = "SYNC_EVENT_SUCCESS";

export const SYNC_EVENT_FAILED = "SYNC_EVENT_FAILED";