export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";
export const CREATE_CLASS_FAILED = "CREATE_CLASS_FAILED";
export const BOOK_CLASS_SUCCESS = "BOOK_CLASS_SUCCESS";
export const BOOK_CLASS_FAILED = "BOOK_CLASS_FAILED";
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_FAILED = "DELETE_CLASS_FAILED";
export const CANCEL_CLASS_SUCCESS = "CANCEL_CLASS_SUCCESS";
export const CANCEL_CLASS_FAILED = "CANCEL_CLASS_FAILED";
export const EDIT_CLASS_SUCCESS = "EDIT_CLASS_SUCCESS";
export const EDIT_CLASS_FAILED = "EDIT_CLASS_FAILED";

