export const CREATE_GOAL_SUCCESS = "CREATE_GOAL_SUCCESS";
export const CREATE_GOAL_FAILED = "CREATE_GOAL_FAILED";

export const DELETE_GOAL_SUCCESS = "DELETE_GOAL_SUCCESS";
export const DELETE_GOAL_FAILED = "DELETE_GOAL_FAILED";

export const EDIT_GOAL_SUCCESS = "EDIT_GOAL_SUCCESS";
export const EDIT_GOAL_FAILED = "EDIT_GOAL_FAILED";

export const CLEAR_GOAL_STATE = "CLEAR_GOAL_STATE";