export const GET_EXERCISE_DATA = 'GET_EXERCISE_DATA';
export const GET_EXERCISE_SUCCESS = 'GET_EXERCISE_SUCCESS';
export const GET_EXERCISE_FAILED = 'GET_EXERCISE_FAILED';
export const GET_NUTRITION_DATA = 'GET_NUTRITION_DATA';
export const GET_NUTRITION_SUCCESS = 'GET__NUTRITION_SUCCESS';
export const GET_NUTRITION_FAILED = 'GET__NUTRITION_FAILED';